# Generated by Django 4.1.2 on 2022-10-27 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=15, verbose_name='Широта')),
                ('longitude', models.FloatField(max_length=15, verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
            ],
            options={
                'db_table': 'pereval_areas',
            },
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Название')),
                ('img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Время добавления')),
            ],
            options={
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='SprActivitiesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
            ],
            options={
                'db_table': 'spr_activities_types',
            },
        ),
        migrations.CreateModel(
            name='PerevalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(default=None, max_length=254, verbose_name='Фамилия')),
                ('name', models.CharField(default=None, max_length=254, verbose_name='Имя')),
                ('otc', models.CharField(max_length=255, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=64, verbose_name='Номер телефона')),
                ('email', models.EmailField(default=None, max_length=254, unique=True, verbose_name='Эл.почта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254, unique=True)),
                ('other_titles', models.CharField(max_length=254)),
                ('connect', models.TextField(blank=True)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('status', models.CharField(choices=[('NEW', 'Новая заявка'), ('PND', 'Заявка на модерации'), ('ACP', 'Модерация прошла успешно'), ('RGT', 'Модерация прошла, информация не принята')], default='NEW', max_length=3)),
                ('level_spring', models.CharField(blank=True, max_length=254, verbose_name='Сложность весной')),
                ('level_summer', models.CharField(blank=True, max_length=254, verbose_name='Сложность летом')),
                ('level_autumn', models.CharField(blank=True, max_length=254, verbose_name='Сложность осенью')),
                ('level_winter', models.CharField(blank=True, max_length=254, verbose_name='Сложность зимой')),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pereval.coords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pereval', to='Pereval.perevaluser')),
            ],
        ),
    ]
